# Generated by Django 5.2 on 2025-10-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthCustomuser',
        ),
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Qa',
        ),
        migrations.DeleteModel(
            name='StudyGroupMembers',
        ),
        migrations.DeleteModel(
            name='StudyGroups',
        ),
    ]
