# Generated by Django 5.2 on 2025-11-09 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='course',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='subjects',
        ),
        migrations.AddField(
            model_name='likes',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.notes'),
        ),
        migrations.AddField(
            model_name='question_subjects',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.notes'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 12:02:40.905647'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 12:02:40.910209', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 12:02:40.901935', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 12:02:40.903046', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 12:02:40.904172'),
        ),
        migrations.AlterField(
            model_name='question_subjects',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.qa'),
        ),
    ]
