# Generated by Django 5.2 on 2025-11-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_remove_notes_course_remove_notes_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='courses',
            field=models.ManyToManyField(through='Auth.Question_subjects', to='Auth.course'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 12:03:04.851502'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 12:03:04.859917', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 12:03:04.844164', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 12:03:04.845715', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 12:03:04.849347'),
        ),
    ]
