# Generated by Django 5.2 on 2025-10-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_answers_created_at_alter_likes_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-13 18:24:30.857187'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-13 18:24:30.863185', null=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-13 18:24:30.855188', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-13 18:24:30.856187'),
        ),
    ]
