# Generated by Django 5.2 on 2025-09-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_authcustomuser_market_notes_notifications_qa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year_of_study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
