# Generated by Django 5.2 on 2025-09-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_customuser_year_of_study'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={},
        ),
        migrations.AlterModelOptions(
            name='qa',
            options={},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
