# Generated by Django 5.2 on 2025-11-09 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_answers_created_at_alter_likes_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='code',
            field=models.CharField(default=uuid.UUID('bc1a7792-ec06-47ad-9953-7c122eb0e1b8'), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 16:18:32.271438'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 16:18:32.275572', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 16:18:32.268246', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 16:18:32.269434', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-09 16:18:32.270268'),
        ),
    ]
