# Generated by Django 5.2 on 2025-11-10 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_notes_code_alter_answers_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='downloads',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-10 12:17:06.530091'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-10 12:17:06.533920', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='code',
            field=models.CharField(default=uuid.UUID('7efb45e3-8208-41f6-a9a8-539a00af83dd'), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='pages',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2025-11-10 12:17:06.526681', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-10 12:17:06.528221', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-10 12:17:06.529044'),
        ),
    ]
