# Generated by Django 5.2 on 2025-09-26 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_notifications_options_alter_qa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.authcustomuser'),
        ),
        migrations.AddField(
            model_name='qa',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.course'),
        ),
        migrations.AddField(
            model_name='qa',
            name='subjects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.authcustomuser'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-26 21:50:38.490753', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-26 21:50:38.490753'),
        ),
    ]
