# Generated by Django 5.2 on 2025-10-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_answers_created_at_alter_likes_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyGroupMembers',
        ),
        migrations.DeleteModel(
            name='StudyGroups',
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-13 18:26:37.666251'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-13 18:26:37.669244', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-13 18:26:37.664266', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-13 18:26:37.665251'),
        ),
    ]
