# Generated by Django 5.2 on 2025-11-10 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_notes_downloads_alter_answers_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='file_type',
            field=models.CharField(default='.pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-10 12:34:13.105087'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-10 12:34:13.110296', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='code',
            field=models.CharField(default=uuid.UUID('c1091ea7-5815-4b55-bf07-3e49d3aebc5b'), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2025-11-10 12:34:13.101543', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-10 12:34:13.103111', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-11-10 12:34:13.104032'),
        ),
    ]
