# Generated by Django 5.2 on 2025-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_alter_notes_options_alter_notifications_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-26 21:51:56.687728', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-26 21:51:56.687728'),
        ),
    ]
