# Generated by Django 5.2 on 2025-12-06 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_category_remove_ratings_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_subjects',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.product'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 18:47:57.206063'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 18:47:57.209273', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='code',
            field=models.CharField(default=uuid.UUID('f9aa4800-d7b4-4f4e-8eb1-232aefc8f365'), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 18:47:57.202026', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 18:47:57.204019', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 18:47:57.205041'),
        ),
    ]
