# Generated by Django 5.2 on 2025-09-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_alter_notes_options_alter_notifications_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-26 21:52:18.219231', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-26 21:52:18.220230'),
        ),
    ]
