# Generated by Django 5.2 on 2025-12-06 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_question_subjects_product_alter_answers_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='courses',
            field=models.ManyToManyField(through='Auth.Question_subjects', to='Auth.course'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 18:49:25.037753'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 18:49:25.042754', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='code',
            field=models.CharField(default=uuid.UUID('a4fdaa28-3169-4e5c-b39b-4ba0f0890a9b'), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 18:49:25.030611', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 18:49:25.032622', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 18:49:25.034136'),
        ),
    ]
