# Generated by Django 5.2 on 2025-12-06 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_product_courses_alter_answers_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_reference',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.product'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.product'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 19:03:53.369895'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 19:03:53.375956', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='code',
            field=models.CharField(default=uuid.UUID('05fb78d6-aea8-4bb3-a642-e733ff1a0eed'), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 19:03:53.367900', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 19:03:53.368893', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-06 19:03:53.369895'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
