# Generated by Django 5.2 on 2025-12-07 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_product_courses_alter_answers_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_reference',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.images'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.product'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-07 12:39:33.205905'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(default=uuid.UUID('769c45f5-8e7d-465b-b024-2dab616d01e2'), max_length=200),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-07 12:39:33.236008', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='code',
            field=models.CharField(default=uuid.UUID('b1923de6-f13c-401c-b206-ab31442528eb'), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2025-12-07 12:39:33.192915', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-07 12:39:33.194903', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-12-07 12:39:33.202903'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
