# Generated by Django 5.2 on 2025-09-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_alter_notifications_created_at_alter_qa_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-26 21:53:43.590189', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-26 21:53:43.593187'),
        ),
    ]
