# Generated by Django 5.2 on 2025-09-26 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_alter_notifications_created_at_alter_qa_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-27 00:12:39.926320', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-27 00:12:39.927316'),
        ),
    ]
