# Generated by Django 5.2 on 2025-09-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_qa_code_alter_notifications_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-27 00:17:11.585028', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-27 00:17:11.586029'),
        ),
    ]
