# Generated by Django 5.2 on 2025-09-26 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_remove_qa_subjects_alter_notifications_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-27 00:20:21.036976', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-09-27 00:20:21.036976'),
        ),
        migrations.CreateModel(
            name='Question_subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.qa')),
            ],
            options={
                'db_table': 'question_subjects',
            },
        ),
    ]
