# Generated by Django 5.2 on 2025-10-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0016_alter_notifications_created_at_alter_qa_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=200)),
                ('image_url', models.FileField(upload_to='media/')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.RemoveField(
            model_name='question_subjects',
            name='id',
        ),
        migrations.AddField(
            model_name='question_subjects',
            name='reference_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-02 09:08:10.024152', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-02 09:08:10.025151'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Image_reference',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.qa')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.images')),
            ],
            options={
                'db_table': 'image_reference',
            },
        ),
        migrations.AddField(
            model_name='qa',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.images'),
        ),
    ]
