# Generated by Django 5.2.4 on 2026-01-01 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0016_alter_address_user_alter_answers_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-01-01 18:41:12.769177'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-01-01 18:41:12.782178', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='code',
            field=models.CharField(default=uuid.UUID('19d0fd9c-37f3-40ea-b933-a8298d82a521'), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2026-01-01 18:41:12.764181', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-01-01 18:41:12.766177', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-01-01 18:41:12.767183'),
        ),
    ]
