# Generated by Django 5.2 on 2025-10-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0017_images_remove_question_subjects_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image_url',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-05 00:24:55.345751', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-05 00:24:55.346753'),
        ),
    ]
