# Generated by Django 5.2 on 2025-10-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0018_rename_image_url_images_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa',
            name='course',
        ),
        migrations.RemoveField(
            model_name='qa',
            name='image',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-05 01:16:24.343684', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-05 01:16:24.345685'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
