# Generated by Django 5.2 on 2025-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0019_remove_qa_course_remove_qa_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='answer_len',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-05 16:31:53.923566', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-05 16:31:53.924566'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
