# Generated by Django 5.2 on 2025-10-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0020_qa_answer_len_alter_notifications_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-10 14:37:33.968877', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='answers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2025-10-10 14:37:33.969878'),
        ),
    ]
