# Generated by Django 5.2.4 on 2026-01-02 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0021_alter_answers_created_at_alter_likes_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-01-02 19:33:07.330791'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-01-02 19:33:07.337338', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='code',
            field=models.CharField(default=uuid.UUID('d9fbe0ef-9161-42b0-9659-e33b547713ba'), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2026-01-02 19:33:07.327795', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-01-02 19:33:07.328788', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-01-02 19:33:07.329788'),
        ),
    ]
