# Generated by Django 5.2.4 on 2026-01-03 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0023_group_slug_alter_answers_created_at_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-01-03 19:19:50.200613'),
        ),
        migrations.AlterField(
            model_name='groupmessages',
            name='messages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-01-03 19:19:50.205607', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='code',
            field=models.CharField(default=uuid.UUID('3bd11a3c-3692-4c7c-814e-ac69d770ce3d'), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2026-01-03 19:19:50.197615', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-01-03 19:19:50.198611', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-01-03 19:19:50.199612'),
        ),
    ]
