# Generated by Django 5.2.4 on 2026-02-08 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0026_alter_address_user_alter_answers_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-02-08 19:06:20.657736'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-02-08 19:06:20.663730', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='code',
            field=models.CharField(default=uuid.UUID('e6bcd258-1db1-4c3c-be0a-6d927741ae4c'), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2026-02-08 19:06:20.652732', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-02-08 19:06:20.654730', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-02-08 19:06:20.655739'),
        ),
    ]
