# Generated by Django 5.2.4 on 2026-04-20 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0028_alter_answers_created_at_alter_likes_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='message_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-04-20 20:13:28.582511'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-04-20 20:13:28.594183', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='code',
            field=models.CharField(default=uuid.UUID('3db7a8dd-e176-473a-a56c-6b564f2eea4a'), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default='2026-04-20 20:13:28.577501', null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-04-20 20:13:28.579500', null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2026-04-20 20:13:28.580501'),
        ),
    ]
