# Generated by Django 5.2 on 2025-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReference',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'image_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='media/')),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionSubjects',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'question_subjects',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='StudyGroupMembers',
        ),
        migrations.DeleteModel(
            name='StudyGroups',
        ),
    ]
